#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Ticket 08: enable GitHub Pages, push master, and confirm the first deploy of
# the profile site. Run from anywhere inside the repository:
#
#   bash .scratch/profile-site/enable-pages.sh
#
# Nothing here needs a secret or the gh CLI. Every check the wizard can do on
# its own (fetching the live pages) it does, and a failed check stops the run
# before anything is recorded; every check that needs eyes or a phone it asks
# about. Safe to re-run: it never records the same outcome twice.

REPO="joramgamer-boop/Selfproj"
REPO_URL="https://github.com/$REPO"
SITE_URL="https://joramgamer-boop.github.io/Selfproj/profile-site/"
ROOT_URL="https://joramgamer-boop.github.io/Selfproj/"
WORKFLOW_URL="$REPO_URL/actions/workflows/publish-profile-site.yml"

# Everything the wizard touches is addressed from the repository root.
cd "$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
README="profile-site/README.md"
TICKET_07=".scratch/profile-site/issues/07-publish-to-github-pages.md"
TICKET_08=".scratch/profile-site/issues/08-enable-pages-and-confirm-deploy.md"

# What the live page must show, read from the content files so that a Tagline
# finalised before the push does not fail the check for the wrong reason.
BIO="profile-site/src/content/bio.md"
DISPLAY_NAME="$(sed -n 's/^firstName: *//p' "$BIO") ($(sed -n 's/^handle: *//p' "$BIO"))"
TAGLINE=$(sed -n 's/^tagline: *//p' "$BIO")
mapfile -t LINK_URLS < <(sed -n 's/^ *"url": *"\([^"]*\)".*/\1/p' profile-site/src/content/links.json)
SECTION_IDS=(bio now projects skills links)

# http_status URL prints the final status code after following redirects
# (curl itself prints 000 when it cannot connect).
http_status() { curl -sS -L -o /dev/null -w '%{http_code}' --max-time 20 "$1" 2>/dev/null || true; }

# fetch URL prints the page body, or nothing when it cannot be fetched.
fetch() { curl -sS -L --max-time 20 "$1" 2>/dev/null || true; }

# check "label" TEXT PATTERN passes when TEXT contains PATTERN (fixed string),
# shows the result, and remembers a failure for stop_if_checks_failed.
CHECKS_FAILED=()
check() {
  local label="$1" text="$2" pattern="$3"
  if printf '%s' "$text" | grep -qF -- "$pattern"; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$label"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$label"
    CHECKS_FAILED+=("$label")
  fi
}

# stop_if_checks_failed ends the run before anything is recorded as confirmed.
stop_if_checks_failed() {
  (( ${#CHECKS_FAILED[@]} )) || return 0
  warn "Stopping so nothing is recorded as confirmed. The live site is missing:"
  for c in "${CHECKS_FAILED[@]}"; do note "  - $c"; done
  say "Compare it with a local build (npm run build inside profile-site/), fix, push, and re-run this wizard."
  exit 1
}

# append_once FILE LINE appends LINE unless FILE already has that exact line,
# so a re-run never records the same outcome twice.
append_once() {
  local file="$1" line="$2"
  grep -qxF -- "$line" "$file" || printf '%s\n' "$line" >> "$file"
}

# record_outcome writes the README line, ticks the tickets' boxes and adds the
# closing comments. Reads TODAY, RUN_KIND and PHONE_OK; sets CLOSING_LINE.
record_outcome() {
  local outcome comment
  if grep -qF "Live at <$SITE_URL>" "$README"; then
    note "README already records the live URL."
  else
    local tmp; tmp=$(mktemp)
    { head -n 1 "$README"; printf '\nLive at <%s>.\n' "$SITE_URL"; tail -n +2 "$README"; } > "$tmp"
    mv "$tmp" "$README"
    printf '  %s✓ wrote%s live URL → %s\n' "$GREEN" "$RESET" "$README"
  fi

  # Ticket 07: only its last box was open, waiting on a green run.
  sed -i 's/^- \[ \] The workflow parses/- [x] The workflow parses/' "$TICKET_07"
  append_once "$TICKET_07" "- $TODAY: Pushed to \`master\`; the workflow ran green $RUN_KIND, build and deploy both, and the site is live (ticket 08)."

  # Ticket 08: tick what was confirmed, then the comment that says what happened.
  outcome="First successful deploy. Pages source set to \"GitHub Actions\", the workflow ran green $RUN_KIND, and the site is live at <$SITE_URL> with <$ROOT_URL> redirecting there."
  if (( PHONE_OK )); then
    sed -i 's/^- \[ \] /- [x] /' "$TICKET_08"
    comment="- $TODAY: $outcome Confirmed on desktop and phone. Closing."
    CLOSING_LINE="Tickets 07 and 08 are closed."
  else
    sed -i '/^- \[ \] \(Open the site on a phone\|Record the live URL\)/!s/^- \[ \] /- [x] /' "$TICKET_08"
    comment="- $TODAY: $outcome On a phone the page scrolls sideways, so the phone box and this ticket stay open until the design pass fixes that."
    CLOSING_LINE="Ticket 07 is closed; ticket 08 stays open for the phone check."
  fi
  grep -q '^## Comments' "$TICKET_08" || printf '\n## Comments\n\n' >> "$TICKET_08"
  append_once "$TICKET_08" "$comment"
  printf '  %s✓ updated%s %s and %s\n' "$GREEN" "$RESET" "$TICKET_07" "$TICKET_08"
}

TOTAL_STAGES=7

banner "Profile site: enable Pages and confirm the first deploy"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Enable GitHub Pages with GitHub Actions as the source"
if curl -sS --max-time 20 "https://api.github.com/repos/$REPO" 2>/dev/null | grep -q '"has_pages": true'; then
  note "GitHub already reports Pages as enabled for $REPO."
  say "Still worth a glance: the source must be \"GitHub Actions\", not a branch."
fi
say "Pages is the one repository setting only the Owner can change."
open_url "$REPO_URL/settings/pages"
step "Under \"Build and deployment\", open the \"Source\" dropdown."
step "Choose \"GitHub Actions\" (not \"Deploy from a branch\"). It saves on selection; there is no Save button."
note "Do this before pushing, so the very first workflow run can deploy instead of failing."
pause "Done? Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Push master so the workflow runs"
git fetch -q origin master || { warn "Could not reach origin. Check the connection and re-run this wizard."; exit 1; }
UNPUSHED=$(git log --oneline origin/master..master)
RUN_KIND=""
if [[ -n "$UNPUSHED" ]]; then
  say "These commits are on master but not on origin yet:"
  printf '%s\n' "$UNPUSHED" | sed 's/^/      /'
  say "Pushing them triggers the \"Publish profile site\" workflow, because they touch profile-site/."
  if confirm "Push master to origin now?"; then
    git push origin master
    printf '  %s✓ pushed%s master\n' "$GREEN" "$RESET"
    RUN_KIND="on the push"
  else
    warn "Not pushed. The workflow will not run until master is on origin."
    say "Push it yourself, then re-run this wizard."
    exit 1
  fi
else
  say "master is already on origin."
  if confirm "Did a push just start a run (or finish one) for the latest commit?"; then
    RUN_KIND="on the push"
  else
    open_url "$WORKFLOW_URL"
    step "Click \"Run workflow\", keep the branch as master, and click the green \"Run workflow\" button."
    pause "Started? Press Enter."
    RUN_KIND="on a run started by hand from the Actions tab"
  fi
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Watch the run until both jobs are green"
open_url "$WORKFLOW_URL"
step "Open the newest run. It has two jobs: build, then deploy."
step "Wait for both to show a green tick. Build takes a minute or two; deploy is quick."
note "If build is red: open the failing step, fix it locally, commit, push, and re-run this wizard."
note "If deploy is red with a message about Pages not being enabled: go back to Stage 1."
if ! confirm "Did the deploy job go green?"; then
  warn "Stopping here. Fix the run, then re-run this wizard."
  exit 1
fi
say "Waiting for the site to answer (the first Pages publish can lag a few minutes)..."
status=000
for _ in $(seq 1 40); do
  status=$(http_status "$SITE_URL")
  [[ "$status" == "200" ]] && break
  printf '  %s… %s, retrying in 15s%s\n' "$DIM" "$status" "$RESET"
  sleep 15
done
if [[ "$status" != "200" ]]; then
  warn "The site still answers $status after 10 minutes. Wait a little and re-run this wizard."
  exit 1
fi
printf '  %s✓ live%s %s\n' "$GREEN" "$RESET" "$SITE_URL"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Confirm the profile page"
say "Automatic checks against the live page:"
PAGE=$(fetch "$SITE_URL")
check "Display Name in the title: $DISPLAY_NAME" "$PAGE" "<title>$DISPLAY_NAME</title>"
check "Tagline: $TAGLINE" "$PAGE" "$TAGLINE"
for id in "${SECTION_IDS[@]}"; do
  check "nav anchor #$id has a target" "$PAGE" "id=\"$id\""
done
for url in "${LINK_URLS[@]}"; do
  check "Link to $url" "$PAGE" "href=\"$url\""
done
stop_if_checks_failed
say "Now with your own eyes:"
open_url "$SITE_URL"
step "The page shows the Display Name \"$DISPLAY_NAME\" and the Tagline under it."
step "Click each nav entry (Bio, Now, Projects, Skills, Links); each jumps to its Section."
step "Under Links, click GitHub and LinkedIn; each opens the right profile."
if ! confirm "Does all of that work?"; then
  warn "Stopping so nothing is recorded as confirmed. Note what was wrong in the ticket, then re-run."
  exit 1
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Confirm the root redirect"
say "Automatic check: the root page carries the redirect."
check "/Selfproj/ redirects to /Selfproj/profile-site/" "$(fetch "$ROOT_URL")" 'url=/Selfproj/profile-site/'
stop_if_checks_failed
open_url "$ROOT_URL"
step "The browser should land on the profile site almost immediately."
if ! confirm "Did it land on the profile site?"; then
  warn "Stopping so nothing is recorded as confirmed. Check the deploy artifact's contents, then re-run."
  exit 1
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Read it on a phone"
say "Open this on your phone:"
say "  $SITE_URL"
step "Scroll top to bottom. The page should read without any sideways scrolling."
note "Layout beyond that belongs to the design pass; only sideways scrolling counts here."
PHONE_OK=0
if confirm "Does it read without horizontal scrolling?"; then
  PHONE_OK=1
else
  warn "The deploy still gets recorded, but the ticket stays open on the phone box."
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Record the live URL and close the ticket"
TODAY=$(date +%F)
CLOSING_LINE=""
record_outcome

if git diff --quiet -- "$README" "$TICKET_07" "$TICKET_08"; then
  note "Nothing new to commit; the outcome was already recorded."
elif confirm "Commit these three files on master?"; then
  git add "$README" "$TICKET_07" "$TICKET_08"
  git commit -q -F - <<MSG
chore(profile-site): record the first deploy on $TODAY

Pages is enabled with GitHub Actions as the source and the site is live at
$SITE_URL. The README records the live URL.
$CLOSING_LINE

Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>
MSG
  printf '  %s✓ committed%s\n' "$GREEN" "$RESET"
  note "This commit touches profile-site/README.md, so pushing it republishes the same site once more."
  if confirm "Push it now?"; then
    git push origin master
    printf '  %s✓ pushed%s\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("push master (git push origin master)")
  fi
else
  SKIPPED+=("commit $README, $TICKET_07 and $TICKET_08")
fi

finish
note "This wizard has done its job; delete .scratch/profile-site/enable-pages.sh when you like."
